#Created by webjeda - http://webjeda.com

title: 彭珊 #Keep it short
email: 862137924@qq.com
 
baseurl: /mysite
 
sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
